version: "3"
services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  signupandsignin:
    build:
      context: .
      dockerfile: SignupandSignin/dockerfile
    ports:
      - "3001:3001"
    depends_on:
      - postgres
    environment:
      - .env.signupandsignin

  registerticket:
    build:
      context: .
      dockerfile: Register-Ticket/dockerfile
    ports:
      - "3002:3002"
    depends_on:
      - postgres
    environment:
      - .env.registerticket

  adminportal:
    build:
      context: .
      dockerfile: Admin-Portal/dockerfile
    ports:
      - "3003:3003"
    depends_on:
      - postgres
    environment:
      - .env.adminportal

volumes:
  postgres_data:
